### ISSUE TITLE
React Testing Library render() not working with embla-carousel-react v8.0.0-rc7

### ISSUE THREAD

**Issue by MWhiteFearless** [davidjerleke/embla-carousel#516]
### Bug is related to

- [x] embla-carousel-react

### Embla Carousel version

- v8.0.0-rc7

### Describe the bug

When upgrading from `embla-carousel-react` v6.2.0 to v8.0.0-rc7, the tests in my repo for components using embla-carousel-react started failing with the error `TypeError: undefined is not a function at Array.map (<anonymous>)` when calling `render()` from react testing library

### CodeSandbox

[- The link to a CodeSandbox that demonstrates the bug clearly.
](https://codesandbox.io/s/embla-carousel-default-react-forked-cgllqg?file=/src/__tests__/EmblaCarousel.test.jsx)

### Steps to reproduce

1. Go to Test tab in the sandbox
2. See that the `renders EmblaCarousel` test fails with the error 
```
undefined is not a function

TypeError: undefined is not a function
    at Array.map (<anonymous>)
```
3. Change the `embla-carousel-react` version to v7.1.0 and refresh the page, see that the `renders EmblaCarousel` test passes

### Expected behavior

The test should pass and the component should render properly.

**Comment by davidjerleke** [comment]
Hi @MWhiteFearless,

Thank you for your complete bug report. I will look into this when possible.

Beat,
David

**Comment by davidjerleke** [comment]
Hi @MWhiteFearless,

I haven't investigated this fully but three things probably will cause problems with React Testing Library that has changed internally in Embla from v7 --> v8:

- Embla is using window.matchMedia now.
- Embla is using ResizeObserver.
- Embla is using MutationObserver.

So let's say you mock window.matchMedia [like this](https://stackoverflow.com/a/53449595/4647781). If run the tests after that and stuff start to work you get a **different error**, then I'm probably right about my guess.

Best,
David

**Comment by MWhiteFearless** [comment]
It works by mocking matchMedia! Tests are passing now, thank you! The stackoverflow suggestion worked perfectly for me.

**Comment by davidjerleke** [comment]
@MWhiteFearless I'm glad it solved the problem. So I'm closing this issue then?

Best,
David

**Comment by MWhiteFearless** [comment]
Yeah works for me! It could be nice to add a note to the documentation in case others run in to this issue. Really appreciate your help!

**Comment by davidjerleke** [comment]
@MWhiteFearless thanks for the tip. I will add it to the release notes for the stable v8 release which is coming soon.

**Comment by davidjerleke** [comment]
@raphaelApard see my [comment](https://github.com/davidjerleke/embla-carousel/issues/516#issuecomment-1626013334).

**Comment by raphaelApard** [comment]
Thanks a lot @MWhiteFearless for completing this issue and @davidjerleke  for your responsiveness ! 
And by the way, thanks for the great work you do with  embla-carousel.
