### ISSUE TITLE
Jest test can't find EmblaCarousel

### ISSUE THREAD

**Issue by raphaelApard** [davidjerleke/embla-carousel#515]
### Bug is related to

- [ ] embla-carousel (core package)

### Embla Carousel version

- v8.0.0-rc7

### Describe the bug

- Jest can't find EmblaCarousel 

I'm writing a test for a script that import and use EmblaCarousel. 
On test running, the following error happens : 

`TypeError: undefined is not a function at Array.map (<anonymous>)`

The same test is working using Embla Carousel version 7.1.0

**Comment by davidjerleke** [comment]
Hi @raphaelApard,

I appreciate the effort to create a bug report but the information provided is not close to  enough. Please read the [contribution guidelines for bug reports](https://github.com/davidjerleke/embla-carousel/blob/master/.github/CONTRIBUTING.md#bug-reports) and provide all information necessary to easily reproduce the problem.

Please let me know if you’re intending to add the missing information.

**Comment by raphaelApard** [comment]
Hi, 

Thanks for you quick reply!
For now, i cannot reproduce my issue on a codesandbox. 

I close this issue and re-open it if i found a way to reproduce it properly.

**Comment by MWhiteFearless** [comment]
I'm having this same issue upgrading from v6.2.0
